Repository micronaut-projects/micronaut-jms, pull requests merged in 2024-01, with the labels that each got.

#471 [jms] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#479 graalvm: add reflect-config.json file
  tests/tasks-activemq-artemis/src/main/resources/META-INF/native-image/io.micronaut.jms.activemq.artemis/reflect-config.json
Labels: bug, relates-to: graal

#475 document and pin SQS version to 2.21.15
  src/main/docs/guide/configuration/sqs.adoc
Labels: bug

#481 build: import aws in settings.gradle
  gradle/libs.versions.toml
  jms-sqs/build.gradle.kts
  settings.gradle
  tests/tasks-sqs/build.gradle.kts
Labels: relates-to: build
